graph LR
  DotNetStandard[.Net Standard] --> Hub
  Hub --> Dashboard

  Unity[Unity *TODO*] --> Hub
  BlazorServerSide[Blazor Server-Side *TODO*] --> Hub
  BlazorWASMSide[Blazor WASM *TODO*] --> Hub
  